Add squash-commit-{title,message}
reitermarkus/automerge pull request #1373
Opened 2022-06-27 18:20 UTC by markelliot

Fixes #147: Enable use of `squash-commit-{title,message}` to customize squash commit.

2022-06-27 19:15 UTC, reitermarkus requested changes

2022-06-27 19:15 UTC, reitermarkus commented on src/helpers.ts
> +  if (squashTitle) {
I think we should remove this. Either way this is a breaking change given the new inputs have default values.

2022-06-27 19:19 UTC, reitermarkus commented
Thanks, @markelliot, I left some comments.

2022-06-27 19:21 UTC, markelliot commented on src/input.ts
> +  squashCommitMessage: string | null
ah I wasn't sure -- it looks like they can't be null based on the types

2022-06-27 19:22 UTC, reitermarkus commented on src/helpers.ts
> +  if (squashTitle) {
Or maybe remove the defaults, since these pretty much mirror the GitHub defaults anyways.

2022-06-27 19:24 UTC, markelliot commented on README.md
> +| Name                               | Required | Description
sorry about the reformat here, I can make the change more concise but VSCode ended up reformatting the entire table by default and I figured not too much harm.

2022-06-27 22:41 UTC, reitermarkus requested changes

2022-06-27 23:40 UTC, markelliot commented on src/input.ts
> +    this.squashCommitMessage = core.getInput('squash-commit-message') || undefined
done

2022-07-01 06:48 UTC, reitermarkus requested changes

2022-07-01 06:48 UTC, reitermarkus commented on src/input.ts
>      this.squashTitle = core.getInput('squash-title') === 'true'
This should now set the `squashCommitTitle` and `this.squashCommitMessage ` templates, if `true`.

2022-07-01 06:50 UTC, reitermarkus commented on README.md
> +| `squash-title`                     | no       | Use the pull request title as the commit message when squashing.                                                                               |
Maybe add a note to this saying it is deprecated.

2022-07-02 17:10 UTC, reitermarkus approved these changes

2022-07-02 17:11 UTC, merged

2022-07-02 17:11 UTC, reitermarkus commented
Thanks, @markelliot!